### ISSUE TITLE
update docs for uncertainty?

### ISSUE THREAD

**Issue by firasm** [drakegroup/sigfig#1]
Hello! Thanks for a really useful package. As a physicist, rounding is extremely frustrating in both python and numpy so I'm considering adding your package as a dependency on my open problem bank.

One thing I noticed, in the docs it says that this statement has this output:

```
>>> from sigfig import round
>>> round(3.14159, uncertainty=0.003639)
'3.142 ± 0.004'
```

But when I try it, I get this instead:

```
>>> round(3.14159, uncertainty=0.003639)
'3.142'
```

Happy to submit a PR to update the readme file, but wanted to know if this was intentional or is there a bug or missing parameter somewhere?

**Comment by MikeBusuttil** [comment]
really appreciate this @firasm !  Also, I'm very interested your open problem bank project - it sounds like a worthwhile endeavour and similar to something I had considered working on a few years back.  I'll be watching to see how it matures and hope to contribute when my schedule allows for it.

As for the issue, this is a bug and I'm grateful for you finding it.  If an uncertainty is supplied by the user then it's assumed that the user wants that uncertainty reflected in the number after its rounded.  The function should supply this by default and I've updated the repo (& PyPI entry) with this fixed along with extra test cases to ensure this doesn't get broken with future updates/fixes.

Thanks @firasm

**Comment by firasm** [comment]
Wonderful! Thanks for the fast work :-)

I suppose my PR and docs update was a quick fix, what you've done is much better!
