### ISSUE TITLE
Typo/misspelled word.

### ISSUE THREAD

**Issue by mpciq** [drakegroup/sigfig#10]
At line 294 there's a misspelled word:
`warn('unregonized argument, skipping %s=%s' % (key, val) )`
I'm guessing that should be unrecognized.

(Thanks for sigfig and making rounding to significant digits easy!)

**Comment by MikeBusuttil** [comment]
thanks for the feedback @mpciq .  Glad you're finding it useful - will do

**Comment by MikeBusuttil** [comment]
FINALLY fixed in #45 and released in v1.3.17
