### ISSUE TITLE
Scientific notation doesn't work with list or tuple output separators

### ISSUE THREAD

**Issue by kiyo-masui** [drakegroup/sigfig#4]
When `sep=list` or `sep=tuple` is specified, the exponent is lost in scientific and engineering notations:

```
>>> # Works fine:
>>> sigfig.round(0.3, uncertainty=0.00023, sep=', ', notation='sci')
'3.000E-1, 0.002E-1'
>>> # But this is very wrong:
>>> sigfig.round(0.3, uncertainty=0.00023, sep=tuple, notation='sci')
('3.000', '0.002')
```

**Comment by kiyo-masui** [comment]
The short-term work around is to use a special character separation, then split the string. The following is equivalent to the desired behavior of the broken line above.

```
>>> tuple(sigfig.round(0.3, uncertainty=0.00023, sep='$', notation='sci').split("$"))
('3.000E-1', '0.002E-1')
```

**Comment by MikeBusuttil** [comment]
fixed, thanks for finding & reporting this!
You can upgrade to the latest version with `pip3 install sigfig -U`
