### ISSUE TITLE
round(13.5224, 2) is formatted as 14.0 and not as 14

### ISSUE THREAD

**Issue by andreabz** [drakegroup/sigfig#48]
I'm using your package for formatting some numeric values.
I found some problems with numbers like 13.5224, when requiring 2 significant digits: it is formatted as 14.0 and not as 14

```
from sigfig import round as sround
sround(13.5224, 2)
```
Thanks.

**Comment by MikeBusuttil** [comment]
Hey @andreabz, that's just how python displays floating point numbers, if you want to see that as a string you have to pass in your number as a string.  This behavior does seem to confuse a lot of users so I'll create a feature request to change the default behavior.  In this case, to see what you'd expect try this:
```py
from sigfig import round as sround
sround(str(13.5224), 2)
```
