### ISSUE TITLE
Type error when rounding numpy.float64

### ISSUE THREAD

**Issue by sb362** [drakegroup/sigfig#5]
## Problem
Passing a `numpy.float64` as the first parameter to `sigfig.round()` results in
```
TypeError: Invalid input type of <class 'numpy.float64'>, expecting 1 of {<class 'sigfig.sigfig._Number'>, <class 'decimal.Decimal'>, <class 'int'>, <class 'NoneType'>, <class 'str'>, <class 'float'>}
```
This issue has been raised before: https://github.com/valdezt/sigfig/issues/5

## Example
```python
from sigfig import round
import numpy as np

round(float(np.float64(3.14)), uncertainty=0.1) # works
round(np.float64(3.14), uncertainty=0.1) # raises TypeError
```

## Possible solution
A possible fix which would support types that inherit from `numbers.Number`, which would include `int`, `float`, `numpy.float64/int32` etc., might be: https://github.com/sb362/sigfig/commit/33361f0c5cb961795b75759ccb4fdd077ce37223

**Comment by MikeBusuttil** [comment]
wow, excellent contribution @sb362 !  If you'd like to make a pull request add some test cases to test_equality.csv (ie. `(float64(3.14),);{'uncertainty':float64(0.1)};'3.1 ± 0.1'`) and numpy.float64 support to test.py `from numpy import float64` for completeness.

Thanks for pitching in :)
